### ISSUE TITLE
BinaryFormatter Error

### ISSUE THREAD

**Issue by benvdh-incentro** [sfc-gh-klochen/sfsnowsightextensions#62]
Hi, 

Today I tried running the `Connect-SFApp` on PowerShell 7.4.5 on Ubuntu 22.04 and after entering my credentials received the following error:

```powershell
Connect-SFApp: BinaryFormatter serialization and deserialization are disabled within this application. See https://aka.ms/binaryformatter for more information.
```

After digging a bit into the code it seems binaryFormatter is used in only 1 line:

https://github.com/sfc-gh-klochen/sfsnowsightextensions/blob/40b4d25dda3fd8124dcc04f20aee49a61b26cda4/SnowflakePS/UtilityDrivers/SnowflakeDriver.cs#L266

It seems to be used to store cookies and/or some other data, so not sure which replacement class should be used to fix this.

**Comment by sfc-gh-jbarrantes** [comment]
I'll look into it @benvdh-incentro

**Comment by sfc-gh-jbarrantes** [comment]
Removed BinaryFormatter usage. Closing this issue
